rebrec_vpnssh_tickets:
    resource: "@RebrecVPNSSHBundle/Controller/TicketsController.php" 
    type:     annotation
    prefix:   /tickets/

rebrec_vpnssh_protocols:
    resource: "@RebrecVPNSSHBundle/Controller/ProtocolController.php" 
    type:     annotation
    prefix:   /protocols/

rebrec_vpnssh_tunnels:
    resource: "@RebrecVPNSSHBundle/Controller/TunnelController.php" 
    type:     annotation
    prefix:   /tunnels/

rebrec_vpnssh_tunnelprofiles:
    resource: "@RebrecVPNSSHBundle/Controller/TunnelProfilesController.php" 
    type:     annotation
    prefix:   /tunnelprofiles/

rebrec_vpnssh_company:
    resource: "@RebrecVPNSSHBundle/Controller/CompanyController.php" 
    type:     annotation
    prefix:   /company/

rebrec_vpnssh_customers:
    resource: "@RebrecVPNSSHBundle/Controller/CustomerController.php" 
    type:     annotation
    prefix:   /customers/

rebrec_vpnssh_homepage:
    resource: "@RebrecVPNSSHBundle/Controller/DefaultController.php" 
    type:     annotation
    prefix:   /
