parameters:
#    rebrec_vpnssh.example.class: Rebrec\Bundle\VPNSSHBundle\Example

services:
#    rebrec_vpnssh.example:
#        class: %rebrec_vpnssh.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
