rebrec_ticketing_homepage:
    path:     /hello/{name}
    defaults: { _controller: RebrecTicketingBundle:Default:index }

rebrec_ticketing_creation_confirmation:
    resource: "@RebrecTicketingBundle/Controller/TicketsController.php" 
    type:     annotation
    prefix:   /tickets/
