parameters:
#    rebrec_ticketing.example.class: Rebrec\Bundle\TicketingBundle\Example

services:
#    rebrec_ticketing.example:
#        class: %rebrec_ticketing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
